name: ci

on:
    push:
        paths-ignore:
            - .github/workflows/elixir-ci.yaml
            - elixir/**

jobs:
    check-commit:
        name: Check

        uses: hxpm/gha/.github/workflows/check-commit.yaml@main
